roletest/roletest/Controllers/postsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using roletest.Models;

namespace roletest.Controllers
{
    public class postsController : Controller
    {
        private Entities db = new Entities();

        // GET: posts
        public ActionResult Index()
        {
            return View(db.posts.ToList());
        }

        // GET: posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            post post = db.posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: posts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name_,description,icon,content,url")] post post)
        {
            if (ModelState.IsValid)
            {
                db.posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        // GET: posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            post post = db.posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name_,description,icon,content,url")] post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            post post = db.posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            post post = db.posts.Find(id);
            db.posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

roletest/roletest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href='https://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
    <script src="~/scripts/alertifyjs/alertify.js"></script>
    <link rel="stylesheet" href="~/Content/alertifyjs/alertify.css">
    <link rel="stylesheet" href="~/Content/alertifyjs/default.css">
    <script>
    
        alertify.defaults = {
            // dialogs defaults
            modal: true,
            basic: false,
            frameless: false,
            movable: true,
            moveBounded: false,
            resizable: true,
            closable: true,
            closableByDimmer: true,
            maximizable: true,
            startMaximized: false,
            pinnable: true,
            pinned: true,
            padding: true,
            overflow: true,
            maintainFocus: true,
            transition: 'pulse',
            autoReset: true,

            // notifier defaults
            notifier: {
                // auto-dismiss wait time (in seconds)  
                delay: 5,
                // default position
                position: 'top-right'
            },

            // language resources 
            glossary: {
                // dialogs default title
                title: 'CodeBar',
                // ok button text
                ok: 'OK',
                // cancel button text
                cancel: 'Cancel'
            },

            // theme settings
            theme: {
                // class name attached to prompt dialog input textbox.
                input: 'ajs-input',
                // class name attached to ok button
                ok: 'ajs-ok',
                // class name attached to cancel button 
                cancel: 'ajs-cancel'
            }
        };
    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <style>
          .affix {
      top:0;
      width: 100%;
      z-index: 9999 !important;
  }
          .nav > li {
 
    border-right: 1px dotted #ededed;
}
  .navbar {
      margin-bottom: 0px;
      box-shadow: 7px 2px 0px #888888;
  }
   .affix ~ .container-fluid {
     position: relative;
     top: 50px;
  }
    </style>
</head>
<body style="padding:0px;background: #ededed;">
    <div class="container-fluid" style="background-color:#F44336;color:#fff;height:200px;">
       @Html.Partial("_bannerPartial")
     
    </div>
    <div id="nav">
    <div class="navbar navbar-default" data-spy="affix" data-offset-top="197">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CodeBar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", style = "font-family: 'Audiowide', cursive;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">             
                    <li>@Html.ActionLink("Learn", "index", "posts")</li>
                    <li>@Html.ActionLink("Teach", "ManageSections", "Teachers")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @{if (User.IsInRole("Student"))
                        {
                           
                          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
    LifeCycle<span class="caret"></span>
</a>

<ul class="dropdown-menu">
                    <li>
   @Html.ActionLink("New LifeCycle","LifeCycle","Students")
                        </li>
    <li>
        @Html.ActionLink("Gallery", "Gallery", "Students")
    </li>
</ul>
                    
</li>
                        }
                        else {
                            <li>@Html.ActionLink("LifeCycle", "LifeCycle", "Students")</li>
                        }
                    }
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
        </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CODEBAR Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

roletest/roletest/Views/Shared/_bannerPartial.cshtml
<link href="~/Content/banner/css" rel="stylesheet" type="text/css">
<link href="~/Content/banner/css(1)" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="~/Content/banner/style.min.css">










    <div id="bg" style="top: 40px; bottom: auto; left: 0px; right: auto;">
        <a class="ion-close-circled close_lightbox" href=""></a>

    </div>

<header>
    <h1 class="logo" style="
    font-family: 'Audiowide', cursive;
"><a href="~/">&nbsp;&nbsp;Codebar</a></h1>
    <h2 class="subline">A website for young kids to learn programming</h2>
    <span class="bg"></span>
    <img class="sun" src="~/Content/banner/sun.svg">
    <img class="plane" src="~/Content/banner/plane.svg">
    <img class="blimp" src="~/Content/banner/blimp.svg">
    </header>