roletest/roletest/Models/Section.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roletest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string SectionName { get; set; }
        public string SectionDetail { get; set; }
        public string TeacherId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}

roletest/roletest/Models/Teacher.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roletest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public string UserId { get; set; }
        public string School { get; set; }
        public string Address { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}

roletest/roletest/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using roletest.Models;

namespace roletest.Controllers
{
    public class SectionsController : Controller
    {
        private Entities db = new Entities();

        // GET: Sections
        public ActionResult Index()
        {
            return View(db.Sections.ToList());
        }

        // GET: Sections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // GET: Sections/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult getProgress()
        {
            return View();
        }
        public ActionResult getStats() {

            return View();
        }

        // POST: Sections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SectionDetial")] Section section)
        {
            if (ModelState.IsValid)
            {
                db.Sections.Add(section);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(section);
        }

        // GET: Sections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Sections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SectionDetial")] Section section)
        {
            if (ModelState.IsValid)
            {
                db.Entry(section).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(section);
        }

        // GET: Sections/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Sections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Section section = db.Sections.Find(id);
            db.Sections.Remove(section);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

roletest/roletest/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace roletest.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        public ActionResult Sections()
        {
            return View();
        }
        public ActionResult SectionManagement()
        {
            return View();
        }
        
    }
}

roletest/roletest/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using roletest.Models;
using Microsoft.AspNet.Identity;
using IdentitySample.Models;

namespace roletest.Controllers
{
    public class TeachersController : Controller
    {
        private Entities db = new Entities();

        // GET: Teachers
        public ActionResult Index()
        {
            var teachers = db.Teachers.Include(t => t.AspNetUser);
            return View(teachers.ToList());
        }
        [Authorize(Roles = "Teacher")]
        public ActionResult ManageSections()
        {
           var userId= User.Identity.GetUserId();
            Teacher teacher = db.Teachers.First(tea => tea.UserId == userId);
            List<Section> listSec = teacher.Sections.ToList();

            return View(listSec);
        }
        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public ActionResult CreateSection()
        {


            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult CreateSection([Bind(Include = "Id,SectionDetail,SectionName")] Section section) {
            var userId = User.Identity.GetUserId();
            Teacher teacher = db.Teachers.First(tea => tea.UserId == userId);
            if (ModelState.IsValid) {
                section.Teacher = teacher;
                db.Sections.Add(section);
                db.SaveChanges();
                return RedirectToAction("ManageSections");
            }

            return View(section);
        }
        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public ActionResult CreateStudent(int? sectionId) {
            RegisterViewModelOfStudentToSection register = new RegisterViewModelOfStudentToSection();
            register.SectionId = (int)sectionId;
            return View();
        }
        [HandleError]
        [Authorize(Roles = "Teacher")]
        public ActionResult StudentManagement(int? id) {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section theSection = db.Sections.First(sec => sec.Id == id);
            if (theSection == null)
            {
                return HttpNotFound();
            }
            

            return View(theSection);
        }
        // GET: Teachers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // GET: Teachers/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,School,Address")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                db.Teachers.Add(teacher);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", teacher.UserId);
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", teacher.UserId);
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,School,Address")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teacher).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", teacher.UserId);
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Teacher teacher = db.Teachers.Find(id);
            db.Teachers.Remove(teacher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

roletest/roletest/Views/Teacher/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<br>
<div class="jumbotron">
    <table ng-show="sections.length > 0" style="width:100%; table-layout:auto;" class="">
        <colgroup>
            <col width="200">
            <col width="130">
            <col width="98">
            <col width="130">
            <col>
            <col>
            <col>
        </colgroup>
        <tbody>
            <tr>
                <th class="manage-th">
                    <a href="" ng-click="order = 'name'">Section</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'login_type'">Login Type</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'grade'">Grade</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'course.name'">Course</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'students.length'">Students</a>
                </th>
                <th class="manage-th">Section Code</th>
                <th class="manage-th"></th>
            </tr>
            <!-- ngRepeat: section in sections | orderBy:order -->
            <tr ng-repeat="section in sections | orderBy:order" style="vertical-align:top" class="ng-scope">
                <td>
                    <span ng-hide="section.editing" style="font-size:18px; padding-top:12px" class="">
                        <a ng-href="#/sections/482236" class="ng-binding" href="../students/index">UOW Smart Start</a>
                    </span>
               
                    
                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">word</span>
                 
                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">5</span>
                    
                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">20-hour</span>
                  
                </td>
                <td class="ng-binding">1</td>
                <td class="ng-binding">
                    YDLNCU
                </td>
          
            </tr><!-- end ngRepeat: section in sections | orderBy:order -->
        </tbody>
    </table>
</div>

<div class="jumbotron">
    <table ng-show="sections.length > 0" style="width:100%; table-layout:auto;" class="">
        <colgroup>
            <col width="200">
            <col width="130">
            <col width="98">
            <col width="130">
            <col>
            <col>
            <col>
        </colgroup>
        <tbody>
            <tr>
                <th class="manage-th">
                    <a href="" ng-click="order = 'name'">Section</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'login_type'">Login Type</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'grade'">Grade</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'course.name'">Course</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'students.length'">Students</a>
                </th>
                <th class="manage-th">Section Code</th>
                <th class="manage-th"></th>
            </tr>
            <!-- ngRepeat: section in sections | orderBy:order -->
            <tr ng-repeat="section in sections | orderBy:order" style="vertical-align:top" class="ng-scope">
                <td>
                    <span ng-hide="section.editing" style="font-size:18px; padding-top:12px" class="">
                        <a ng-href="#/sections/482236" class="ng-binding" href="../students/index">UOW Smart Start</a>
                    </span>


                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">word</span>

                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">5</span>

                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">20-hour</span>

                </td>
                <td class="ng-binding">1</td>
                <td class="ng-binding">
                    YDLNCU
                </td>

            </tr><!-- end ngRepeat: section in sections | orderBy:order -->
        </tbody>
    </table>
</div>

<div class="jumbotron">
    <table ng-show="sections.length > 0" style="width:100%; table-layout:auto;" class="">
        <colgroup>
            <col width="200">
            <col width="130">
            <col width="98">
            <col width="130">
            <col>
            <col>
            <col>
        </colgroup>
        <tbody>
            <tr>
                <th class="manage-th">
                    <a href="" ng-click="order = 'name'">Section</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'login_type'">Login Type</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'grade'">Grade</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'course.name'">Course</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'students.length'">Students</a>
                </th>
                <th class="manage-th">Section Code</th>
                <th class="manage-th"></th>
            </tr>
            <!-- ngRepeat: section in sections | orderBy:order -->
            <tr ng-repeat="section in sections | orderBy:order" style="vertical-align:top" class="ng-scope">
                <td>
                    <span ng-hide="section.editing" style="font-size:18px; padding-top:12px" class="">
                        <a ng-href="#/sections/482236" class="ng-binding" href="#/sections/482236">123</a>
                    </span>


                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">word</span>

                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">5</span>

                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">20-hour</span>

                </td>
                <td class="ng-binding">1</td>
                <td class="ng-binding">
                    YDLNCU
                </td>

            </tr><!-- end ngRepeat: section in sections | orderBy:order -->
        </tbody>
    </table>
</div>

<div class="jumbotron">
    <table ng-show="sections.length > 0" style="width:100%; table-layout:auto;" class="">
        <colgroup>
            <col width="200">
            <col width="130">
            <col width="98">
            <col width="130">
            <col>
            <col>
            <col>
        </colgroup>
        <tbody>
            <tr>
                <th class="manage-th">
                    <a href="" ng-click="order = 'name'">Section</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'login_type'">Login Type</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'grade'">Grade</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'course.name'">Course</a>
                </th>
                <th class="manage-th">
                    <a href="" ng-click="order = 'students.length'">Students</a>
                </th>
                <th class="manage-th">Section Code</th>
                <th class="manage-th"></th>
            </tr>
            <!-- ngRepeat: section in sections | orderBy:order -->
            <tr ng-repeat="section in sections | orderBy:order" style="vertical-align:top" class="ng-scope">
                <td>
                    <span ng-hide="section.editing" style="font-size:18px; padding-top:12px" class="">
                        <a ng-href="#/sections/482236" class="ng-binding" href="#/sections/482236">123</a>
                    </span>


                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">word</span>

                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">5</span>

                </td>
                <td>
                    <span ng-hide="section.editing" class="ng-binding">20-hour</span>

                </td>
                <td class="ng-binding">1</td>
                <td class="ng-binding">
                    YDLNCU
                </td>

            </tr><!-- end ngRepeat: section in sections | orderBy:order -->
        </tbody>
    </table>
</div>
<h2>Index</h2>

roletest/roletest/Views/Teacher/SectionManagement.cshtml
@{
    ViewBag.Title = "SectionManagement";
}

<h2>SectionManagement</h2>

<ul class="nav nav-tabs">
    <li role="presentation" id="1" class="tabb active"><a href="#">Stuedent Management</a></li>
    <li role="presentation" id="2" class="tabb"><a href="#">View Progress  </a></li>
    <li role="presentation" id="3" class="tabb"><a href="#">View stats</a></li>
</ul>
<div id="studentManagement">
    @Html.Action("IndexPartial", "Students")
    </div>
<div id="viewProgress" hidden>
    @Html.Action("getProgress","Sections")
    </div>
<div id="viewStats">
    </div>
<script>
    var activeTab = 1;
    $(".tab").click(
       function () {
           var clickId = $(this).attr('id');
       if(clickId==1){
       $("#studentManagement").show();
       $("#viewProgress").hide();
       $("#1").attr('class')=activeyukukil
       }else{
       $("#viewProgress").show();
        $("#studentManagement").hide();
       }


       }
        )

</script>